#!/usr/bin/env perl

use 5.010;
use strict;
use utf8;
use warnings;

use File::Slurper qw(read_text);

binmode STDOUT, ":utf8";

my @w;

for my $file (<../devdata/*Chinese*>) {
    my $ct = read_text($file);

    # chengyu's listed under hanzi looks like traditional form, we only want
    # traditional form, so we remove them
    $ct =~ s!<h3>一</h3>.+!!s;

    while ($ct =~ m!^<li><a href="/wiki[^>]+>(.+?)</a></li>!gm) {
        push @w, $1;
    }
}

say for sort @w;
